matrix:
  - name: Markdown (Dansk)
    aspell:
      lang: da
      ignore-case: true
    dictionary:
      wordlists:
        - .wordlist.txt
    pipeline:
      - pyspelling.filters.markdown:
    sources:
      - '**/*.md'

  - name: Markdown (Engelsk)
    aspell:
      lang: en
      ignore-case: true
    dictionary:
      wordlists:
        - .wordlist.txt
    pipeline:
      - pyspelling.filters.markdown:
    sources:
      - '**/*.md'
