title: Just the Docs Template
description: A starter template for a Jekyll site using the Just the Docs theme!

theme: just-the-docs
custom_css:
  - "assets/css/accordion.css"


url: https://just-the-docs.github.io
