title: System Design Docs
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

mermaid:
  # Specifies the version of the Mermaid library to use for diagram rendering
  # Select a Mermaid version from the available options at the provided URL: https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"