name: Spellcheck

on:
  pull_request:
    branches: [main]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

    - name: Install aspell dictionaries
      run: |
        sudo add-apt-repository universe
        sudo apt-get update
        sudo apt-get install -y aspell-en aspell-da

      - name: Run pyspelling spellcheck
        uses: igsekor/pyspelling-any@v0.0.2
        with:
          configFile: '.spellcheck.yml'
